CREATE TABLE refresh_token
(
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    token           VARCHAR(255) NOT NULL UNIQUE,
    user_id         BIGINT       NOT NULL,
    expiration_date TIMESTAMP    NOT NULL,
    CONSTRAINT fk_refresh_token_user
        FOREIGN KEY (user_id)
            REFERENCES users (id)
);