ALTER TABLE orders ADD COLUMN started_at TIMESTAMP DEFAULT NULL;
ALTER TABLE orders ADD COLUMN finished_at TIMESTAMP DEFAULT NULL;

ALTER TABLE orders ALTER COLUMN total_order_price TYPE NUMERIC(10, 2);
ALTER TABLE orders ALTER COLUMN total_fees_value TYPE NUMERIC(10, 2);
ALTER TABLE orders ALTER COLUMN final_total_price TYPE NUMERIC(10, 2);
ALTER TABLE orders ALTER COLUMN additional_comment TYPE VARCHAR(500);