CREATE TABLE tables
(
    id               BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    number_table     BIGINT,
    chairs_available BIGINT,
    status           VARCHAR(255),
    admin_id         BIGINT,
    CONSTRAINT pk_tables PRIMARY KEY (id),
    CONSTRAINT fk_tables_on_admin FOREIGN KEY (admin_id) REFERENCES admins (id)
);